### ISSUE TITLE
"modid.mixins.json" left as default name causing incompatabilities

### ISSUE THREAD

**Issue by milkev** [dev-lukas/armor-extended-fabric#1]
modid should be replaced with your modid. if two mods leave this file as the default name the game will not open.
you will also have to update your fabric.mod.json mixin entry to the new file name.

in general, your mod has a lot of modid instances that should be replaced with your actual modid, but the mixins one is the only one (that i know of) that will actually cause issues

https://github.com/dev-lukas/armor-extended-fabric/blob/1.19/src/main/resources/modid.mixins.json
![image](https://user-images.githubusercontent.com/22010128/203615382-b5db05f4-0a64-4ce6-9788-ed69b4cbfbad.png)
(i will be posting the same issue for the other mod as well)
(edit: except they are mia and have no github. RIP)

**Comment by dev-lukas** [comment]
Thank you for brining this to my attention! I already updated some modid related stuff last time, but totally forgot the mixins. Should be now patched and an updated version is being uploaded to Curseforge.
